In [1]:
import pandas as pd
import joblib

In [3]:
model = joblib.load("shipment_delay_model.pkl")

FileNotFoundError: [Errno 2] No such file or directory: 'shipment_delay_model.pkl'

In [ ]:
model

NameError: name 'model' is not defined

In [ ]:
import pandas as pd
import joblib

In [4]:
model = joblib.load("shipment_delay_model.pkl")

FileNotFoundError: [Errno 2] No such file or directory: 'shipment_delay_model.pkl'

In [ ]:
model

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

In [ ]:
model.feature_names_in_

array(['Product type', 'SKU', 'Price', 'Availability',
       'Number of products sold', 'Revenue generated',
       'Customer demographics', 'Stock levels', 'Lead times',
       'Order quantities', 'Shipping times', 'Shipping carriers',
       'Shipping costs', 'Supplier name', 'Location', 'Lead time',
       'Production volumes', 'Manufacturing lead time',
       'Manufacturing costs', 'Inspection results', 'Defect rates',
       'Transportation modes', 'Routes', 'Costs'], dtype='<U23')

In [ ]:
new_shipment = pd.DataFrame({
    "Product type": ["skincare"],
    "SKU": ["SKU101"],
    "Price": [55.5],
    "Availability": [120],
    "Number of products sold": [300],
    "Revenue generated": [4500.75],
    "Customer demographics": ["Female"],
    "Stock levels": [60],
    "Lead times": [12],
    "Order quantities": [150],
    "Shipping times": [7],
    "Shipping carriers": ["Carrier A"],
    "Shipping costs": [80.5],
    "Supplier name": ["Supplier X"],
    "Location": ["Mumbai"],
    "Lead time": [12],
    "Production volumes": [500],
    "Manufacturing lead time": [10],
    "Manufacturing costs": [250.75],
    "Inspection results": ["Pass"],
    "Defect rates": [2.5],
    "Transportation modes": ["Road"],
    "Routes": ["Route A"],
    "Costs": [300.25]
})

In [ ]:
prediction = model.predict(new_shipment)
prediction

ValueError: DataFrame.dtypes for data must be int, float, bool or category. When categorical type is supplied, the experimental DMatrix parameter`enable_categorical` must be set to `True`.  Invalid columns:Product type: str, SKU: str, Customer demographics: str, Shipping carriers: str, Supplier name: str, Location: str, Inspection results: str, Transportation modes: str, Routes: str

In [ ]:
X_train.columns

NameError: name 'X_train' is not defined

In [ ]:
X_train.columns

NameError: name 'X_train' is not defined

In [ ]:
new_shipment.dtypes

Product type                   str
SKU                            str
Price                      float64
Availability                 int64
Number of products sold      int64
Revenue generated          float64
Customer demographics          str
Stock levels                 int64
Lead times                   int64
Order quantities             int64
Shipping times               int64
Shipping carriers              str
Shipping costs             float64
Supplier name                  str
Location                       str
Lead time                    int64
Production volumes           int64
Manufacturing lead time      int64
Manufacturing costs        float64
Inspection results             str
Defect rates               float64
Transportation modes           str
Routes                         str
Costs                      float64
dtype: object

In [ ]:
type(model)

xgboost.sklearn.XGBClassifier

In [ ]:
new_shipment.dtypes

Product type                   str
SKU                            str
Price                      float64
Availability                 int64
Number of products sold      int64
Revenue generated          float64
Customer demographics          str
Stock levels                 int64
Lead times                   int64
Order quantities             int64
Shipping times               int64
Shipping carriers              str
Shipping costs             float64
Supplier name                  str
Location                       str
Lead time                    int64
Production volumes           int64
Manufacturing lead time      int64
Manufacturing costs        float64
Inspection results             str
Defect rates               float64
Transportation modes           str
Routes                         str
Costs                      float64
dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv("../dataset/supply_chain_data.csv")

In [ ]:
label_encoders = {}

for col in df.select_dtypes(include="object").columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col].astype(str))
    label_encoders[col] = le

C:\Users\shiva\AppData\Local\Temp\ipykernel_14576\61030170.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

In [ ]:
for col in label_encoders:
    new_shipment[col] = label_encoders[col].transform(
        new_shipment[col].astype(str)
    )

ValueError: y contains previously unseen labels: 'SKU101'

In [ ]:
df.head()

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,1,0,69.808006,55,802,8661.996792,2,58,7,96,...,4,29,215,29,46.279879,2,0.226410,2,1,187.752075
1,2,1,14.843523,95,736,7460.900065,0,53,30,37,...,4,23,517,30,33.616769,2,4.854068,2,1,503.065579
2,1,12,11.319683,34,8,9577.749626,3,1,10,88,...,4,12,971,27,30.688019,2,4.580593,0,2,141.920282
3,2,23,61.163343,68,83,7766.836426,2,23,13,59,...,3,24,937,18,35.624741,0,4.746649,1,0,254.776159
4,2,34,4.805496,26,871,2686.505152,2,5,3,56,...,2,5,414,3,92.065161,0,3.145580,0,0,923.440632

In [ ]:
new_shipment = pd.DataFrame({
    "Product type": [1],
    "SKU": [0],
    "Price": [69.808006],
    "Availability": [55],
    "Number of products sold": [802],
    "Revenue generated": [8661.996792],
    "Customer demographics": [2],
    "Stock levels": [58],
    "Lead times": [7],
    "Order quantities": [96],
    "Shipping times": [4],
    "Shipping carriers": [2],
    "Shipping costs": [2.956572],
    "Supplier name": [0],
    "Location": [4],
    "Lead time": [29],
    "Production volumes": [215],
    "Manufacturing lead time": [29],
    "Manufacturing costs": [46.279879],
    "Inspection results": [2],
    "Defect rates": [0.226410],
    "Transportation modes": [2],
    "Routes": [1],
    "Costs": [187.752075]
})

In [ ]:
new_shipment

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,1,0,69.808006,55,802,8661.996792,2,58,7,96,...,4,29,215,29,46.279879,2,0.22641,2,1,187.752075

In [ ]:
prediction = model.predict(new_shipment)
prediction

array([0])

In [ ]:
if prediction[0] == 1:
    print("🚚 Shipment will be Delayed")
else:
    print("✅ Shipment will Arri On Time")

✅ Shipment will Arrive On Time

In [ ]:
from xgboost import XGBClassifier
import joblib
import os

# Train the model
model = XGBClassifier(
    random_state=42,
    eval_metric="logloss"
)

model.fit(X_train, y_train)

# Create models folder if it doesn't exist
os.makedirs("models", exist_ok=True)

# Save the trained model
joblib.dump(model, "models/shipment_delay_model.pkl")

print("✅ Model trained successfully!")
print("✅ Model saved at: models/shipment_delay_model.pkl")